### ISSUE TITLE
Make this app 100% client side

### ISSUE THREAD

**Issue by slig** [javascript-obfuscator/javascript-obfuscator-ui#1]
Research to see if it's possible to run the obfuscator on the browser.

**Comment by Xzlash** [comment]
well?

**Comment by slig** [comment]
Not happening on my part. Feel free to try and post back here what you find.

**Comment by Ashesh3** [comment]
@slig Seems like this is indeed possible now, thanks to 

`<script src="https://cdn.jsdelivr.net/npm/javascript-obfuscator/dist/index.browser.js"/>`

Demo: https://jsfiddle.net/89bvqzj6/


Seems need to modify this: 
https://github.com/javascript-obfuscator/javascript-obfuscator-ui/blob/e43acda21ef1cf307eb777c3cb87f81611ad57c5/App/actions/index.js#L15

to something like 

`JavaScriptObfuscator.obfuscate(n.code,n.options);`

then return it in the expected json format like:

`{"code":obf._obfuscatedCode,"sourceMap":obf._sourceMap}`


Hope it helps!

**Comment by sanex3339** [comment]
Done with Web Worker. Please, test it.
