### ISSUE TITLE
Code obfuscated with this is blocked by McAfee

### ISSUE THREAD

**Issue by durga73** [javascript-obfuscator/javascript-obfuscator-ui#14]
I have obfuscated the code with this tool, then McAfee onacess scan is showing that file as trojan virus ditected as JS/Nemucod.ya. Can you let me know why it is throwing this error is there any malicious code is included. How to verify it doesn't contain malicious code ?

**Comment by sanex3339** [comment]
Related to https://github.com/javascript-obfuscator/javascript-obfuscator/issues/51

**Comment by slig** [comment]
No malicious code is included in any way.

You should run the tool locally if you don't believe, check the main repo @ github.com/javascript-obfuscator/javascript-obfuscator to see the instructions.
