### ISSUE TITLE
Move UI on new domain

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/javascript-obfuscator-ui#19]
Now i have `obfuscator.io` domain, so it will nice to add this domain as custom domain for herokuapp

**Comment by slig** [comment]
Nice domain!

It will certainly be better because then we can move it to a VPS. The one paid dyno I'm currently using on Heroku is over capacity.

**Comment by sanex3339** [comment]
I just upped you UI on `obfuscator.io` domain. Right now it's full copy of your UI, but i wan't to slightly change it to improve markup on the mobile devices.

Please, can you add redirect from your site to my site.

Also, i running it on heroku hosting with one `hobby` dyno. Right now it haven't SSL certificate, but i plan to add it.

**Comment by slig** [comment]
Done!

It's important for you to use a SSL certificate otherwise Google might lower your rank.

**Comment by sanex3339** [comment]
Added SSL cert. It should redirect from `http://obfuscator.io` and `https://obfuscator.io` to `https://www.obfuscator.io`

**Comment by sanex3339** [comment]
Switched from heroku hosting on gandi simple hosting, because of SSL problem with root `obfuscator.io` domain. Everything is ok
