### ISSUE TITLE
Examples page

### ISSUE THREAD

**Issue by slig** [javascript-obfuscator/javascript-obfuscator-ui#2]
Have some sort of examples pages showing the obfuscated code working.

For instance, find some HTML 5 web game [here](https://github.com/leereilly/games), host it with different options of the obfuscator and explain to the user: "Try to use the Developer Tool on this page" or "Here you can see source maps working".

**Comment by sanex3339** [comment]
I replaced the descriptions of the old options with the `readme.md` from the `javascript-obfuscator` package. So some options now have examples.
