### ISSUE TITLE
Upload JavaScript Files

### ISSUE THREAD

**Issue by carverdo** [javascript-obfuscator/javascript-obfuscator-ui#20]
Hi.
I usually use your "Copy & Paste JavaScript Code" tab but today tried using "Upload JavaScript Files" but nothing happens when I drag and drop. Yesterday, perhaps coincidentally, my browser froze immediately after.

If relevant, I'm using Chrome.

**Comment by slig** [comment]
Hi,

I cannot reproduce that here. After uploading, clicking on the first tab shows the code as expected.

It's not clear, but this online tool is more like a playground than a proper way to obfuscate your production code, specially larger files.

I recommend downloading and using the NPM package for all your production needs.

**Comment by haitham7** [comment]
hi @slig can you please show me who I use NPM package to convert my all js files

**Comment by sanex3339** [comment]
Hi, you should use CLI 
https://github.com/javascript-obfuscator/javascript-obfuscator#obfuscate-directory-recursively
