### ISSUE TITLE
Use 301 redirect

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/javascript-obfuscator-ui#22]
Hi. Can you use 301 redirect instead of 302? 301 redirect is required for correct google search indexing.

**Comment by slig** [comment]
Done!

Can you please change my email on the footer to my blog address? instead of `mailto:...@gmail.com` to `https://www.tiagoserafim.com/`?

Also, are you planning to keep this repo updated with your latest changes?

**Comment by sanex3339** [comment]
Thank you.

I will update your blog address in a hour or so.

Yes, i will keep this repo updated and currently i investigating a way to keep both repos (gandi repo for deploy and this repo) to being in sync.

**Comment by slig** [comment]
Thank you!

If you need any help, I'm glad to help.

**Comment by sanex3339** [comment]
Updated your contacts

**Comment by sanex3339** [comment]
Updated repo
