### ISSUE TITLE
Error when code contains object spread syntax

### ISSUE THREAD

**Issue by Lumox100** [javascript-obfuscator/javascript-obfuscator-ui#23]
I get the following error when trying to obfuscate Javascript code that uses the spread syntax to merge objects into one object using https://obfuscator.io/.

Error: Unknown node type ExperimentalSpreadProperty.

var newObj = {...obj1, ...obj2}
obj1 and obj2 only contain properties, no methods.

Array spread syntax does not cause any problems.

**Comment by sanex3339** [comment]
Please, recreate issue here:
https://github.com/javascript-obfuscator/javascript-obfuscator/issues

**Comment by sanex3339** [comment]
But looks like it is third-party library problem. Related to estraverse or escodegen.
