### ISSUE TITLE
windows npm run updatesemantic is error

### ISSUE THREAD

**Issue by manyhelp** [javascript-obfuscator/javascript-obfuscator-ui#29]
windows10:
   npm run updatesemantic

cp App/styles/theme.config ./node_modules/semantic-ui-less/theme.config;

error

**Comment by israndi** [comment]
javascript-obfuscator-ui on windows
===================================

you must install win-node-env
> npm install -g win-node-env

> git clone https://github.com/javascript-obfuscator/javascript-obfuscator-ui.git
> cd javascript-obfuscator-ui

in file package.json
edit =================
"updatesemantic": "cp App/styles/theme.config ./node_modules/semantic-ui-less/theme.config; rm -Rf ./node_modules/semantic-ui-less/site; cp -R App/styles/site ./node_modules/semantic-ui-less/"
to =================
"updatesemantic": "copy App\\styles\\theme.config node_modules\\semantic-ui-less && xcopy /E /I App\\styles\\site node_modules\\semantic-ui-less\\site"

> yarn install [or] npm install

Running the express server
> node server.js

The server runs on http://localhost:3000/ from web browser

**Comment by sanex3339** [comment]
Closed as old
