### ISSUE TITLE
REQ: Custom Identifier Names Generator

### ISSUE THREAD

**Issue by v1nce** [javascript-obfuscator/javascript-obfuscator-ui#42]
Would it be possible to use a custom ING ? (by providing a function ?)

Instead of short names, I'd like to provide confusing names :

-  characters that look alike l,i,1,I...
-  utf-8 character (mathematical ones for instance)
-  non western alphabet...

**Comment by slig** [comment]
Hi, please see this issue on the other repo https://github.com/javascript-obfuscator/javascript-obfuscator/issues/268 you can comment there to +1 this feature.

**Comment by zamotkin** [comment]
Guys, I'll try to merge all ideas and to implement it.

**Comment by v1nce** [comment]
I learnt that what I try to achieve is named visual spoofing.
More about it here : http://websec.github.io/unicode-security-guide/visual-spoofing/

Samples of confusing characters 
https://unicode.org/cldr/utility/confusables.jsp?a=test&r=None

**Comment by sanex3339** [comment]
Hi. Right now you can use new `dictionary` identifier names generator that will out soon in `0.20.0` version.

**Comment by sanex3339** [comment]
Closed. Same issue is already in the main repo.
