### ISSUE TITLE
Please See the image below

### ISSUE THREAD

**Issue by AinCoder** [javascript-obfuscator/javascript-obfuscator-ui#43]
Would you like to say what's the problem here?
It's not going ahead :(
The last command was **npm run webpack:dev**
![Screenshot_13](https://user-images.githubusercontent.com/26634947/72689177-eedeaf00-3b38-11ea-8897-9e2bc93a6d6e.png)

**Comment by sanex3339** [comment]
Sorry, have no idea

**Comment by sanex3339** [comment]
Closed as old. Fell free to create a new issue if this problem still exists.
