### ISSUE TITLE
accept multiple values for parameters with plus icon inputs

### ISSUE THREAD

**Issue by ErinPo** [javascript-obfuscator/javascript-obfuscator-ui#45]
It would be nice if the GUI supported entering multiple values at once in the inputs featuring the plus icon. It would facilitate entering many items. The GUI could show what separator is expected such as comma, semicolon, space, new line, etc.

**Comment by sanex3339** [comment]
Not sure that it the best idea, because in some places separator can be used as a value, especially in `reservedStrings` option
