### ISSUE TITLE
Obfuscator Not Working good.

### ISSUE THREAD

**Issue by 69Steve** [javascript-obfuscator/javascript-obfuscator-ui#46]
There are a lot of peoples that can deobfuscate my codes and get the code easy!
and i tried all obfuscations settings but they could debofuscate my codes and understand all thigns
and deobfuscate the variables
example if i obfuscate this code:
function test() {
console.log ("hi");
}
test();

then they can deobfuscate the code and get it like this:
function test() {
console.log ("hi");
}
test();

i ready don't know how they can deobfuscate my codes.

here is my settings.
if someone know how to fix that so please tell me 👍 
![image](https://user-images.githubusercontent.com/45514708/86167514-f1e1c080-bb16-11ea-8c7d-566899457712.png)

**Comment by sanex3339** [comment]
It is impossible to restore original names of the renamed variables or properties.
All other things can be restored in some way but it takes a time depends on code size and obfuscation level.

Maybe you used obfuscator with `sourceMap` option and serve source maps alongside the obfuscated code?

Can you show me more detailed examples of your obfuscated code and how it was restored? You can send it via my email
