### ISSUE TITLE
https://obfuscator.io/ UI broken

### ISSUE THREAD

**Issue by robly** [javascript-obfuscator/javascript-obfuscator-ui#53]
It looks like the drop down for 'String Array Encoding' was changed and is now broken.

Here is a screen shot and error message.

ReferenceError: Validation failed. errors:
`stringArrayEncoding` errors:
    - each value in stringArrayEncoding must be one of the following values: none,base64,rc4

![2020-09-03_15-16-17](https://user-images.githubusercontent.com/1971188/92178969-983c9180-edf8-11ea-969e-d68950ca94c8.png)

**Comment by sanex3339** [comment]
Press 'resetOptions' and try again. Or clear your local storage on this site.

**Comment by sanex3339** [comment]
Also before it, please past here the options that are stored inside localStorage.

**Comment by sanex3339** [comment]
Upd: i know the reason of this bug. Will update the web-ui in 5 minutes.

**Comment by sanex3339** [comment]
Should be fixed now, just reload the page and your `stringArrayOption` will be reset to the default value `none`.
Reopen this issue if this bug still exists.
