### ISSUE TITLE
The input for obfuscating the code is not visible?

### ISSUE THREAD

**Issue by afuggini** [javascript-obfuscator/javascript-obfuscator-ui#8]

**Comment by slig** [comment]
Looks like I broke it on Firefox. Could you please confirm your browser version?

**Comment by slig** [comment]
Should be working now, please try again. Thanks for reporting.

**Comment by afuggini** [comment]
I was using latest Google Chrome on Mac OS.

**Comment by afuggini** [comment]
@slig Ok solved now, thanks!
